export const vehicleConstants = {
    ADD_ECONOMY_VEHICLE: "ADD_ECONOMY_VEHICLE",
    ADD_ESTATE_VEHICLE: "ADD_ESTATE_VEHICLE",
    ADD_LUXURY_VEHICLE: "ADD_LUXURY_VEHICLE",
    ADD_SUV_VEHICLE: "ADD_SUV_VEHICLE",
    ADD_CARGO_VEHICLE: "ADD_CARGO_VEHICLE"
}

export const customerConstants = {
    ADD_CUSTOMER: "ADD_CUSTOMER",
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER"
}